# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  # Define custom self-hosted runner labels
  labels:
    - linux-arm64
    - linux-arm64-xl
    - self-hosted-arm64
    - self-hosted-arm64-2xl
    - blacksmith-4vcpu-ubuntu-2404-arm
    - blacksmith-16vcpu-ubuntu-2404-arm
