# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  # Define custom self-hosted runner labels
  labels:
    - linux-x64
    - linux-x64-xl
    - linux-arm64
    - linux-arm64-xl
    - self-hosted-x64
    - self-hosted-x64-2xl
    - self-hosted-arm64
    - self-hosted-arm64-2xl
