name: 'Gradle post-build actions'
description: |
  Saves the build gradle artifacts and publishes test reports.

inputs:
  github-token:
    description: 'Github token to run publish of JUnit reports in'
    required: true

runs:
  using: composite
  steps:
    - name: 'Publish Test Report'
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        token: ${{ inputs.github-token }}
        report_paths: "**/build/test-results/test/TEST-*.xml"

    - name: 'Publish Integration Test Report'
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        token: ${{ inputs.github-token }}
        check_name: "JUnit Integration-Test Report"
        report_paths: "**/build/test-results/integrationTest/TEST-*.xml"
