name: 'Docker Compose Setup'
description: 'Start Docker Compose and wait for containers to be healthy'
author: 'Your Organization'

inputs:
  docker-compose-path:
    description: 'File path of the docker compose file'
    required: true
  timeout:
    description: 'Timeout in seconds to wait for containers to be healthy'
    required: false
    default: '60'
  interval:
    description: 'Interval in seconds between health checks'
    required: false
    default: '2'

runs:
  using: 'composite'
  steps:
    - name: Start Docker Compose
      shell: bash
      run: |
        docker compose -f ${{ inputs.docker-compose-path }} up -d
    
    - name: Wait for containers to be healthy
      shell: bash
      run: |
        echo "Waiting for containers to become healthy..."
        timeout=${{ inputs.timeout }}
        interval=${{ inputs.interval }}
        end=$((SECONDS + timeout))
        
        containers=$(docker compose -f ${{ inputs.docker-compose-path }} ps -q)
        
        while [ $SECONDS -lt $end ]; do
          unhealthy=0
        
          for container in $containers; do
            health=$(docker inspect --format='{{.State.Health.Status}}' "$container" 2>/dev/null || echo "none")
            if [ "$health" != "healthy" ]; then
              unhealthy=$((unhealthy + 1))
            fi
          done
        
          if [ "$unhealthy" -eq 0 ]; then
            echo "All containers are healthy."
            exit 0
          fi
        
          sleep $interval
        done
        
        echo "Timeout reached. Some containers are still unhealthy:"
        docker compose -f ${{ inputs.docker-compose-path }} ps
        exit 1