name: Build Docker Image
on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
        default: 'eu-west-1'
        description: 'AWS region'
      stage:
        required: true
        type: string
        description: 'stage being released (dev,staging,production'
      service:
        required: true
        type: string
        description: 'Name of the service being released'
      docker-file-name:
        required: false
        type: string
        description: Name of the docker file to be built
        default: "Dockerfile"
    secrets:
      GHL_USERNAME:
        required: true
        description: 'Github Username (Gradle plugin)'
      GHL_PASSWORD:
        required: true
        description: 'Github Password (Gradle plugin)'
      AWS_ACCESS_KEY_ID:
        required: true
        description: 'AWS access key id'
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: 'AWS secret access key'
      SLACK_APP_TOKEN:
        required: true
        description: 'Slack app token'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Publish progress message to slack
        uses: monta-app/slack-notifier-cli-action@main
        id: publish-slack
        with:
          status: "progress"
          title: ${{ inputs.service }} - Build workflow 🏗️
          slack-token: ${{ secrets.SLACK_APP_TOKEN }}
          slack-channel-id: "C01KL9FUPNK"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build docker container
        id: build-container
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          SERVICE_NAME: ${{ inputs.service }}
          STAGE: ${{ inputs.stage }}
          DOCKER_FILE_NAME: ${{ inputs.docker-file-name }}
        run: |
          ECR_IMAGE_URL=$ECR_REGISTRY/$SERVICE_NAME-$STAGE
          docker build --build-arg=GHL_USERNAME=${{ secrets.GHL_USERNAME }} --build-arg=GHL_PASSWORD=${{ secrets.GHL_PASSWORD }} -f $DOCKER_FILE_NAME -t $ECR_IMAGE_URL:$IMAGE_TAG .
          docker push $ECR_IMAGE_URL:$IMAGE_TAG
          docker tag $ECR_IMAGE_URL:$IMAGE_TAG $ECR_IMAGE_URL:latest
          docker push $ECR_IMAGE_URL:latest
          echo "::set-output name=ECR_IMAGE_URL:$IMAGE_TAG::$ECR_IMAGE_URL:$IMAGE_TAG"
        shell: bash
      - name: Publish result message to slack
        uses: monta-app/slack-notifier-cli-action@main
        if: ${{ always() }}
        with:
          status: ${{ job.status }}
          title: ${{ inputs.service }} - Build workflow 🏗️
          slack-token: ${{ secrets.SLACK_APP_TOKEN }}
          slack-channel-id: "C01KL9FUPNK"
          slack-message-id: ${{ steps.publish-slack.outputs.slack-message-id }}
