# Reusable workflow to convert runner size strings to actual GitHub runner names
# Maps "normal" to "linux-x64" and "large" to "linux-x64-xl" for consistent runner selection
# Github issue: https://github.com/orgs/community/discussions/10773
name: Convert runner size to runner name
on:
  workflow_call:
    inputs:
      runner-size:
        required: true
        type: string
        description: "Runner size (normal or large)"
    outputs:
      runner-name:
        description: "Converted runner name"
        value: ${{ jobs.convert.outputs.runner-name }}

jobs:
  convert:
    runs-on: ubuntu-latest
    outputs:
      runner-name: ${{ steps.convert-runner.outputs.runner-name }}
    steps:
      - name: Convert runner size to runner name
        id: convert-runner
        run: |
          case "${{ inputs.runner-size }}" in
            "normal")
              echo "runner-name=linux-x64" >> $GITHUB_OUTPUT
              ;;
            "large")
              echo "runner-name=linux-x64-xl" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "Error: Invalid runner size '${{ inputs.runner-size }}'"
              exit 1
              ;;
          esac
