name: Test
on:
  workflow_call:
    inputs:
      runner-size:
        required: false
        type: string
        description: 'Runner size for the component-runner-size-converter'
      service-name:
        required: false
        type: string
        description: 'Proper name for your service i.e OCPP Service, Vehicle Service'
      service-emoji:
        required: false
        type: string
        description: 'An emoji to identify your service by :)'
      gradle-module:
        required: false
        type: string
        description: 'Name of the gradle module being tested'
      java-version:
        required: false
        type: string
        default: "21"
        description: 'Java version to use'
      gradle-args:
        required: false
        type: string
        default: "--no-daemon --parallel"
        description: 'Additional Gradle arguments'
    secrets:
      GHL_USERNAME:
        required: true
        description: 'Github Username (Gradle plugin)'
      GHL_PASSWORD:
        required: true
        description: 'Github Password (Gradle plugin)'

permissions:
  contents: read
  actions: read

jobs:
  setup:
    name: Setup
    runs-on: linux-arm64
    outputs:
      runner-name: ${{ steps.runner.outputs.runner-name }}
    steps:
      - name: Get runner name
        id: runner
        uses: monta-app/github-workflows/.github/actions/runner-size-converter@main
        with:
          runner-size: ${{ inputs.runner-size }}
  test:
    name: Test
    needs: setup
    runs-on: ${{ needs.setup.outputs.runner-name }}
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "corretto"
          java-version: ${{ inputs.java-version }}
          cache: 'gradle'
      - name: Test project
        env:
          GHL_USERNAME: ${{ secrets.GHL_USERNAME }}
          GHL_PASSWORD: ${{ secrets.GHL_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}
        uses: monta-app/github-workflows/.github/actions/gradle-multi-module@main
        with:
          gradle-module: ${{ inputs.gradle-module }}
          gradle-tasks: 'test'
          gradle-args: ${{ inputs.gradle-args }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: test-result-${{ inputs.gradle-module || 'root' }}
          path: |
            build/reports/tests/test
            **/build/reports/tests/test
            /home/runner/.gradle/daemon/**/daemon-*.out.log
          retention-days: 2
          overwrite: true
