name: IT Tests

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  actions: read # This is required for 8398a7/action-slack

on:
  workflow_call:
    inputs:
      mode:
        required: false
        type: string
        description: 'Docker setup mode - all, services or unit'
        default: "all"
      profiles:
        required: false
        type: string
        description: 'Docker compose profiles used'
        default: "app"
      tested-project-folder:
        required: false
        type: string
        default: "tested-project"
        description: 'base folder where PHP-server is pulled'
      gradle-module:
        required: true
        type: string
        description: 'gradle module to be built'
      php-branch:
        required: false
        type: string
        default: "staging"
        description: 'gradle module to be built'
      java-distribution:
        required: false
        type: string
        default: 'corretto'
      java-version:
        required: false
        type: string
        default: '17'

jobs:
  it-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout PHP-Server
        with:
          repository: monta-app/server
          ref: ${{ inputs.php-branch }}
          token: ${{ secrets.PAT }}
          fetch-depth: 1

      - name: Setup docker compose
        uses: ./.github/actions/setup-docker-compose
        with:
          mode: "services"
          profiles: "app,identity"
          aws-account-id: ${{ secrets.STAGING_AWS_ACCOUNT_ID }}

      #######################################################
      #######################################################

      - uses: actions/checkout@v4
        name: Checkout Project
        with:
          path: ./${{ inputs.tested-project-folder }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
          cache: 'gradle'
      - name: Test project
        env:
          GHL_USERNAME: ${{ secrets.GHL_USERNAME }}
          GHL_PASSWORD: ${{ secrets.GHL_PASSWORD }}
          GRADLE_MODULE: ${{ inputs.gradle-module }}
        run: |
          cd ${{ inputs.tested-project-folder }}
          if [ -z "$GRADLE_MODULE" ]
          then
            ./gradlew --no-daemon integrationTest -i
          else
            ./gradlew --no-daemon $GRADLE_MODULE:integrationTest -i
          fi
        shell: bash
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: |
            ./${{ inputs.tested-project-folder }}/**/reports/tests/test
            /home/runner/.gradle/daemon/**/daemon-*.out.log
          retention-days: 2
