name: Auto-create PR to promote staging to main

on:
  workflow_call:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO: ${{github.repository}}

jobs:
  auto_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Auto create production PR if it does not exist
        run: |
          OPEN_PR=$(gh pr view staging --repo $REPO --jq 'select(.state == "OPEN" and .baseRefName == "main")' --json number,state,baseRefName || echo "")

          if [ -z "$OPEN_PR" ]; then
            TITLE='release: production'
            BODY='Update main with latest changes from staging. Approve this PR and merge it by commenting `/monta-merge`.'
            gh pr create \
              --repo $REPO \
              --base main \
              --head staging \
              --title "$TITLE" \
              --body "$BODY"
          else
            echo "PR already exists"
          fi
