name: Build and test (React/TypeScript with Bun)
on:
  workflow_call:
    inputs:
      runner-size:
        required: false
        type: string
        description: "Runner to use for the job (normal, or large)"
        default: "normal"
      bun-version:
        required: false
        type: string
        default: 'latest'
        description: "Bun version to use"
      working-directory:
        required: false
        type: string
        default: '.'
        description: "Working directory for frontend code"
      build-timeout-minutes:
        required: false
        type: number
        description: "Timeout for the build job in minutes"
        default: 15
      lint-command:
        required: false
        type: string
        default: 'bun run lint'
        description: "Command to run for linting"
      build-command:
        required: false
        type: string
        default: 'bun run build'
        description: "Command to run for building"
      test-command:
        required: false
        type: string
        default: 'bun run test'
        description: "Command to run for testing (optional)"
      docker-compose-path:
        required: false
        type: string
        description: "File path of the docker compose file"
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      runner-name: ${{ steps.runner.outputs.runner-name }}
    steps:
      - name: Check PR title
        uses: monta-app/github-workflows/.github/actions/pr-title-check@v3
      - name: Get runner name
        id: runner
        uses: monta-app/github-workflows/.github/actions/runner-size-converter@v3
        with:
          runner-size: ${{ inputs.runner-size }}
  lint-build-test:
    name: Lint & Build & Test
    needs: setup
    runs-on: ${{ needs.setup.outputs.runner-name }}
    timeout-minutes: ${{ inputs.build-timeout-minutes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Start Docker Compose
        if: ${{ inputs.docker-compose-path }}
        run: |
          docker compose -f ${{ inputs.docker-compose-path }} up -d
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: bun install
      - name: Lint check
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.lint-command }}
      - name: Run tests
        if: ${{ inputs.test-command != '' }}
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.test-command }}
      - name: Build check
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.build-command }}
      - name: Disable man-db trigger refreshes (https://github.com/actions/runner-images/issues/10977)
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
          sudo dpkg-reconfigure man-db
      - name: Install lcov
        run: |
          sudo apt-get install lcov
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
